"""Derived blocks leave the RENDER; the post navigation replaces them (design 253ac996, amendment
75e7494a, under the redesign build 8079ae0f).

Ingest types each embedded derived block of an archive post as its own Section with a
`block_role` (the series callout, the hand TOC, the hand Previous / Next lines). The sources
stay byte-identical (the source-identity DoD, 13753cbf (4)); the build takes the blocks out of
what Quarto renders instead, and projects what they restated from the graph:

1. the PLAN, per post source: each derived block named by its role and its FINGERPRINT (its
   link targets in order, which Pandoc passes through unchanged), plus the post's NAVIGATION —
   its series position (part N of M, previous / next, the series page) from the Series page's
   listed members, and its COLLECTIONS (the topic pages whose Lens lists it). A page's listed
   members are the ones the series and topic pages themselves list under the profile, so the
   navigation never points at a page the profile does not render.
2. the DATA file and ONE Lua filter, generated into the git-ignored `_derived/` of the project:
   the filter drops the top-level block each entry names (a callout-tip Div, a bullet list, a
   header, matched by role shape AND fingerprint) and inserts the navigation; it carries no
   classification rule of its own (the classifier is ingest's, `cjm_markdown_decompose_core
   .blocks`), and it appends one report line per document it acted on.
3. the CHECK after the render, failing closed: every planned block dropped exactly once and
   every planned navigation inserted, or the build names the post."""

import json
import posixpath
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from cjm_context_graph_primitives.query import PropertyPredicate
from cjm_dev_graph_schema.vocab import DevNodeKinds
from cjm_markdown_decompose_core.blocks import (block_link_targets, HAND_TOC, SERIES_CALLOUT,
                                                SERIES_NAV_LINE)

from . import factlayer as F
from .runtime import GraphHandle

DERIVED_DIR = "_derived"                       # generated, git-ignored; Quarto skips `_` dirs
DATA_FILE = "derived-blocks.json"
FILTER_FILE = "derived-blocks.lua"
REPORT_FILE = "derived-blocks.report.jsonl"
ROLES = (SERIES_CALLOUT, HAND_TOC, SERIES_NAV_LINE)

# A thematic-break line inside a hand TOC's span: ingest joined the closing rule to the block,
# so the filter drops the HorizontalRule that follows the list too.
_RULE_LINE_RE = re.compile(r"^[ \t]*-{3,}[ \t]*\r?$", re.M)

LUA_FILTER = r'''-- GENERATED by site-build from the notes graph (design 253ac996): do not edit, it is overwritten.
-- Drops the derived blocks the graph names for this document and inserts its navigation.
-- It holds no classification rule: an entry names a block by role and link-target fingerprint.
local dir = quarto.project.directory .. "/_derived/"

local function read_all(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local s = f:read("a")
  f:close()
  return s
end

local DATA = pandoc.json.decode(read_all(dir .. "derived-blocks.json") or "{}", false)

local SHAPE = {
  -- Quarto hands user filters a callout as a placeholder Div typed by attribute; a plain
  -- callout-tip Div is the same block before that conversion
  series_callout = function(el)
    return el.t == "Div" and (el.classes:includes("callout-tip")
      or el.attributes["__quarto_custom_type"] == "Callout")
  end,
  hand_toc = function(el) return el.t == "BulletList" end,
  series_nav_line = function(el) return el.t == "Header" end,
}

local function targets(el)
  local out = {}
  el:walk({ Link = function(l) table.insert(out, l.target) end })
  return out
end

local function same(a, b)
  if #a ~= #b then return false end
  for i = 1, #a do if a[i] ~= b[i] then return false end end
  return true
end

function Pandoc(doc)
  local input = quarto.doc.input_file
  local root = quarto.project.directory .. "/"
  local key = input:sub(1, #root) == root and input:sub(#root + 1) or input
  local entry = DATA[key]
  if entry == nil then return nil end
  local drops = entry.drop or {}
  local counts = {}
  for i = 1, #drops do counts[i] = 0 end
  local kept = {}
  local skip_rule = false
  for _, el in ipairs(doc.blocks) do
    local dropped = false
    if skip_rule and el.t == "HorizontalRule" then
      dropped = true
    else
      local t = nil
      for i, d in ipairs(drops) do
        if SHAPE[d.role] and SHAPE[d.role](el) then
          t = t or targets(el)
          if same(t, d.links) then
            counts[i] = counts[i] + 1
            if counts[i] == 1 then dropped = true; skip_rule = d.rule == true end
            break
          end
        end
      end
      if not dropped then skip_rule = false end
    end
    if not dropped then table.insert(kept, el) end
  end
  local blocks = {}
  if entry.nav and entry.nav ~= "" then
    for _, b in ipairs(pandoc.read(entry.nav, "markdown").blocks) do table.insert(blocks, b) end
  end
  for _, b in ipairs(kept) do table.insert(blocks, b) end
  doc.blocks = blocks
  local rows = {}
  for i, d in ipairs(drops) do table.insert(rows, { role = d.role, count = counts[i] }) end
  local f = io.open(dir .. "derived-blocks.report.jsonl", "a")
  if f then
    f:write(pandoc.json.encode({ input = key, dropped = rows, nav = (entry.nav or "") ~= "" }) .. "\n")
    f:close()
  end
  return doc
end
'''


def _md_link(title: str, href: str) -> str:
    return f"[{title.replace('[', '(').replace(']', ')')}]({href})"


def render_nav(
    series: Optional[Dict[str, Any]],  # {title, href, part, total, prev, next} ({title, href} each or None)
    collections: List[Dict[str, str]],  # [{title, href}] in the topic pages' key order
) -> str:  # The navigation's markdown ("" when the post has neither)
    """The post navigation: the series position, then the collections line, as simple callouts."""
    out: List[str] = []
    if series:
        lines = [f"**Part {series['part']} of {series['total']}** in {_md_link(series['title'], series['href'])}"]
        steps = []
        if series.get("prev"):
            steps.append("Previous: " + _md_link(series["prev"]["title"], series["prev"]["href"]))
        if series.get("next"):
            steps.append("Next: " + _md_link(series["next"]["title"], series["next"]["href"]))
        if steps:
            lines.append(" · ".join(steps))
        out.append('::: {.callout-tip .derived-nav appearance="simple" icon=false}\n'
                   + "  \n".join(lines) + "\n:::\n")
    if collections:
        label = "In the collection" if len(collections) == 1 else "In the collections"
        out.append('::: {.callout-note .derived-nav appearance="simple" icon=false}\n'
                   + label + ": " + ", ".join(_md_link(c["title"], c["href"]) for c in collections)
                   + "\n:::\n")
    return "\n".join(out)


def _post_href(
    note_id: str,
    src: str,                              # The post's source, relative to the root
    pages: Dict[str, Dict[str, Any]],      # redirect_plan's {subject: {active, superseded}}
) -> str:
    """A post's public path: its active site_path fact, else the path its source renders at."""
    page = pages.get(note_id)
    if page:
        return page["active"]
    d = posixpath.dirname(src)
    return "/" + (d + "/" if posixpath.basename(src).startswith("index.") else src.rsplit(".", 1)[0] + ".html")


async def derived_plan(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    planned_pages: List[Dict[str, Any]],  # page_plan's pages (each with `listed`: the note ids it lists, in order; `href`; `title`)
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    inputs: List[str],                  # The profile's input documents (absolute, from `quarto inspect`)
) -> Dict[str, Any]:  # {posts: {source: {drop, nav}}, counts, errors}
    """Plan every rendered post's drops and navigation. A derived block with no link target
    cannot be named to the filter, so it refuses rather than stays silently."""
    root = Path(website_root).resolve()
    rendered = {Path(d).resolve().relative_to(root).as_posix() for d in inputs}
    notes = {str(F.nid(n)): n for n in await F.load_label(gx, DevNodeKinds.NOTE)}
    src_of: Dict[str, str] = {}
    for nid, n in notes.items():
        raw = F.prop(n, "path")
        p = Path(str(raw)).resolve() if raw else None
        if p is not None and p.is_relative_to(root) and p.relative_to(root).as_posix() in rendered:
            src_of[nid] = p.relative_to(root).as_posix()
    posts: Dict[str, Dict[str, Any]] = {}
    errors: List[Dict[str, Any]] = []
    sections = await F.load_label_where(gx, DevNodeKinds.SECTION,
                                        [PropertyPredicate("block_role", "not_null")])
    for s in sorted(sections, key=lambda s: (str(F.prop(s, "note_id")), int(F.prop(s, "order") or 0))):
        role, nid = str(F.prop(s, "block_role") or ""), str(F.prop(s, "note_id") or "")
        if nid not in src_of or role not in ROLES:
            continue
        text = str(F.prop(s, "raw") or F.prop(s, "text") or "")
        links = block_link_targets(text)
        if not links:
            errors.append({"kind": "derived-unnamed", "source": src_of[nid], "role": role,
                           "section": str(F.nid(s)),
                           "why": "a derived block with no link target cannot be named to the render filter"})
            continue
        drop = {"role": role, "links": links}
        if role == HAND_TOC and _RULE_LINE_RE.search(text):
            drop["rule"] = True
        posts.setdefault(src_of[nid], {"drop": [], "nav": ""})["drop"].append(drop)
    series_nav: Dict[str, Dict[str, Any]] = {}
    collections: Dict[str, List[Dict[str, str]]] = {}
    for page in planned_pages:
        members = [m for m in page["listed"] if m in src_of]
        if page["kind"] == DevNodeKinds.SERIES:
            for i, m in enumerate(members):
                step = lambda j: ({"title": str(F.prop(notes[members[j]], "title") or ""),
                                   "href": _post_href(members[j], src_of[members[j]], pages)}
                                  if 0 <= j < len(members) else None)
                series_nav[m] = {"title": page["title"], "href": page["href"], "part": i + 1,
                                 "total": len(members), "prev": step(i - 1), "next": step(i + 1)}
        else:
            for m in members:
                collections.setdefault(m, []).append({"title": page["title"], "href": page["href"]})
    for nid in set(series_nav) | set(collections):
        nav = render_nav(series_nav.get(nid), collections.get(nid, []))
        posts.setdefault(src_of[nid], {"drop": [], "nav": ""})["nav"] = nav
    counts = {"posts": len(posts), "series_nav": len(series_nav), "collections": len(collections)}
    for role in ROLES:
        counts[role] = sum(1 for p in posts.values() for d in p["drop"] if d["role"] == role)
    return {"posts": dict(sorted(posts.items())), "counts": counts, "errors": errors}


def write_derived(
    website_root: str,         # The site project root
    plan: Dict[str, Any],      # derived_plan's report
) -> Dict[str, Any]:  # {written: [file names], report_cleared}
    """Write the data file and the filter (only what changed) and clear the report."""
    d = Path(website_root) / DERIVED_DIR
    d.mkdir(exist_ok=True)
    written = []
    for name, text in ((DATA_FILE, json.dumps(plan["posts"], indent=1, ensure_ascii=False) + "\n"),
                       (FILTER_FILE, LUA_FILTER)):
        p = d / name
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")
            written.append(name)
    report = d / REPORT_FILE
    cleared = report.exists()
    report.unlink(missing_ok=True)
    return {"written": written, "report_cleared": cleared}


def check_derived(
    website_root: str,     # The site project root
    plan: Dict[str, Any],  # derived_plan's report
) -> Dict[str, Any]:  # {reported, errors}
    """After the render: every planned post reported, each named block dropped exactly once, and
    its navigation inserted. A post the filter never reported fails (the filter did not run)."""
    report = Path(website_root) / DERIVED_DIR / REPORT_FILE
    rows: Dict[str, List[Dict[str, Any]]] = {}
    if report.exists():
        for line in report.read_text(encoding="utf-8").splitlines():
            if line.strip():
                r = json.loads(line)
                rows.setdefault(r["input"], []).append(r)
    errors: List[Dict[str, Any]] = []
    for src, entry in plan["posts"].items():
        got = rows.get(src)
        if not got:
            errors.append({"kind": "derived-unreported", "source": src,
                           "why": "the render filter never reported this post (it did not run)"})
            continue
        last = got[-1]
        for want, have in zip(entry["drop"], last["dropped"]):
            if have["count"] != 1:
                errors.append({"kind": "derived-drop", "source": src, "role": want["role"],
                               "count": have["count"],
                               "why": "a named derived block was not dropped exactly once"})
        if bool(entry["nav"]) != bool(last["nav"]):
            errors.append({"kind": "derived-nav", "source": src,
                           "why": "the post's navigation was not inserted"})
    return {"reported": len(rows), "errors": errors}
