"""Derived blocks leave the RENDER; the post navigation replaces them (design 253ac996, amendment
75e7494a, under the redesign build 8079ae0f).

Ingest types each embedded derived block of an archive post as its own Section with a
`block_role` (the series callout, the hand TOC, the hand Previous / Next lines). The sources
stay byte-identical (the source-identity DoD, 13753cbf (4)); the build takes the blocks out of
what Quarto renders instead, and projects what they restated from the graph:

1. the PLAN, per post source: each derived block named by its role and its FINGERPRINT (its
   link targets in order, which Pandoc passes through unchanged), plus the post's NAVIGATION —
   its series position (part N of M, previous / next, the series page) from the Series page's
   listed members, and its COLLECTIONS (the topic pages whose Lens lists it). A page's listed
   members are the ones the series and topic pages themselves list under the profile, so the
   navigation never points at a page the profile does not render.
2. the DATA file and ONE Lua filter, generated into the git-ignored `_derived/` of the project:
   the filter drops the top-level block each entry names (a callout-tip Div, a bullet list, a
   header, matched by role shape AND fingerprint) and inserts the navigation; it carries no
   classification rule of its own (the classifier is ingest's, `cjm_markdown_decompose_core
   .blocks`), and it appends one report line per document it acted on.
3. the CHECK after the render, failing closed: every planned block dropped exactly once and
   every planned navigation inserted, or the build names the post.

The site-chrome includes (the about-author and questions callouts) are derived blocks too
(design 39c51c15 (5)): an entry names the partial, the filter parses it and drops the blocks it
expanded to, and the post's END MATTER — the author strip of `postpage` — closes the page."""

import json
import posixpath
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml
from cjm_context_graph_primitives.query import PropertyPredicate
from cjm_dev_graph_schema.vocab import DevNodeKinds
from cjm_markdown_decompose_core.blocks import (block_link_targets, CHROME_INCLUDE, HAND_TOC,
                                                include_target, SERIES_CALLOUT, SERIES_NAV_LINE)

from . import factlayer as F
from .runtime import GraphHandle

DERIVED_DIR = "_derived"                       # generated, git-ignored; Quarto skips `_` dirs
DATA_FILE = "derived-blocks.json"
FILTER_FILE = "derived-blocks.lua"
REPORT_FILE = "derived-blocks.report.jsonl"
ROLES = (SERIES_CALLOUT, HAND_TOC, SERIES_NAV_LINE, CHROME_INCLUDE)

# A thematic-break line inside a hand TOC's span: ingest joined the closing rule to the block,
# so the filter drops the HorizontalRule that follows the list too.
_RULE_LINE_RE = re.compile(r"^[ \t]*-{3,}[ \t]*\r?$", re.M)

LUA_FILTER = r'''-- GENERATED by site-build from the notes graph (design 253ac996): do not edit, it is overwritten.
-- Drops the derived blocks the graph names for this document, inserts its navigation at the top
-- and its end matter (the author strip, design 39c51c15 (5)) at the bottom.
-- It holds no classification rule: an entry names a block by role and link-target fingerprint,
-- or a site-chrome include by the partial it includes.
local dir = quarto.project.directory .. "/_derived/"

local function read_all(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local s = f:read("a")
  f:close()
  return s
end

local DATA = pandoc.json.decode(read_all(dir .. "derived-blocks.json") or "{}", false)

local function doc_entry()
  local input = quarto.doc.input_file
  local root = quarto.project.directory .. "/"
  local key = input:sub(1, #root) == root and input:sub(#root + 1) or input
  return key, DATA[key]
end

local SHAPE = {
  -- Quarto hands user filters a callout as a placeholder Div typed by attribute; a plain
  -- callout-tip Div is the same block before that conversion
  series_callout = function(el)
    return el.t == "Div" and (el.classes:includes("callout-tip")
      or el.attributes["__quarto_custom_type"] == "Callout")
  end,
  hand_toc = function(el) return el.t == "BulletList" end,
  series_nav_line = function(el) return el.t == "Header" end,
}

-- A chrome include's signature, from the partial itself: the callout it expands to (type,
-- title, text) and the block types around it (the about-author partial opens on a rule)
local SIGS = {}
local function include_sig(path)
  if SIGS[path] ~= nil then return SIGS[path] end
  local text = read_all(quarto.project.directory .. path)
  local sig = false
  if text then
    sig = { pre = {}, post = {} }
    for _, b in ipairs(pandoc.read(text, "markdown").blocks) do
      local ctype = nil
      if b.t == "Div" and sig.callout == nil then
        for _, c in ipairs(b.classes) do ctype = ctype or c:match("^callout%-(.+)$") end
      end
      if ctype then
        sig.callout = { type = ctype, title = b.attributes.title or "", text = pandoc.utils.stringify(b) }
      elseif sig.callout == nil then
        table.insert(sig.pre, b.t)
      else
        table.insert(sig.post, b.t)
      end
    end
    if sig.callout == nil then sig = false end
  end
  SIGS[path] = sig
  return sig
end

local function targets(el)
  local out = {}
  el:walk({ Link = function(l) table.insert(out, l.target) end })
  return out
end

local function same(a, b)
  if #a ~= #b then return false end
  for i = 1, #a do if a[i] ~= b[i] then return false end end
  return true
end

-- Pass 1: a callout a chrome include expanded to becomes a marker naming its drop entry
local function mark_includes(c)
  local _, entry = doc_entry()
  if entry == nil then return nil end
  for i, d in ipairs(entry.drop or {}) do
    local sig = d.role == "chrome_include" and include_sig(d.include) or nil
    if sig and c.type == sig.callout.type and pandoc.utils.stringify(c.title or "") == sig.callout.title
        and pandoc.utils.stringify(c.content or "") == sig.callout.text then
      return pandoc.Div({}, pandoc.Attr("", { "derived-drop" }, { { "drop", tostring(i) } }))
    end
  end
  return nil
end

-- Pass 2: every marker leaves, at ANY depth (a post whose raw HTML leaves a div open nests the
-- rest of its body, the include with it), and the partial's blocks around the callout leave
-- with it from the same block list
local MARKS = {}
local function drop_marked(blocks)
  local _, entry = doc_entry()
  if entry == nil then return nil end
  local out, skip_after, changed = {}, {}, false
  for _, el in ipairs(blocks) do
    if el.t == "Div" and el.classes:includes("derived-drop") then
      changed = true
      local i = tonumber(el.attributes["drop"])
      MARKS[i] = (MARKS[i] or 0) + 1
      local sig = include_sig(entry.drop[i].include)
      for j = #sig.pre, 1, -1 do
        if #out > 0 and out[#out].t == sig.pre[j] then table.remove(out) end
      end
      skip_after = { table.unpack(sig.post) }
    elseif #skip_after > 0 and el.t == skip_after[1] then
      table.remove(skip_after, 1)
      changed = true
    else
      skip_after = {}
      table.insert(out, el)
    end
  end
  if changed then return pandoc.Blocks(out) end
  return nil
end

-- Pass 3: drop the named top-level blocks, insert the navigation and the end matter, report
local function apply(doc)
  local key, entry = doc_entry()
  if entry == nil then return nil end
  -- The header's projected metadata: the kind label, the dated facts (design 39c51c15 (2))
  if entry.meta then
    for k, v in pairs(entry.meta.set or {}) do doc.meta[k] = pandoc.MetaString(v) end
    for _, k in ipairs(entry.meta.unset or {}) do doc.meta[k] = nil end
  end
  local drops = entry.drop or {}
  local counts = {}
  for i = 1, #drops do counts[i] = 0 end
  local kept = {}
  for i, d in ipairs(drops) do
    if d.role == "chrome_include" then counts[i] = MARKS[i] or 0 end
  end
  local skip_rule = false
  for _, el in ipairs(doc.blocks) do
    local dropped = false
    if skip_rule and el.t == "HorizontalRule" then
      dropped = true
    else
      local t = nil
      for i, d in ipairs(drops) do
        if SHAPE[d.role] and SHAPE[d.role](el) then
          t = t or targets(el)
          if same(t, d.links) then
            counts[i] = counts[i] + 1
            if counts[i] == 1 then dropped = true; skip_rule = d.rule == true end
            break
          end
        end
      end
      if not dropped then skip_rule = false end
    end
    if not dropped then table.insert(kept, el) end
  end
  local blocks = {}
  if entry.nav and entry.nav ~= "" then
    for _, b in ipairs(pandoc.read(entry.nav, "markdown").blocks) do table.insert(blocks, b) end
  end
  for _, b in ipairs(kept) do table.insert(blocks, b) end
  if entry["end"] and entry["end"] ~= "" then
    for _, b in ipairs(pandoc.read(entry["end"], "markdown").blocks) do table.insert(blocks, b) end
  end
  doc.blocks = blocks
  local rows = {}
  for i, d in ipairs(drops) do table.insert(rows, { role = d.role, count = counts[i] }) end
  local f = io.open(dir .. "derived-blocks.report.jsonl", "a")
  if f then
    f:write(pandoc.json.encode({ input = key, dropped = rows, nav = (entry.nav or "") ~= "",
                                 ["end"] = (entry["end"] or "") ~= "" }) .. "\n")
    f:close()
  end
  return doc
end

return {
  { Callout = mark_includes },
  { Blocks = drop_marked },
  { Pandoc = apply },
}
'''


def _md_link(title: str, href: str) -> str:
    return f"[{title.replace('[', '(').replace(']', ')')}]({href})"


def render_nav(
    series: Optional[Dict[str, Any]],  # {title, href, part, total, prev, next} ({title, href} each or None)
    collections: List[Dict[str, str]],  # [{title, href}] in the topic pages' key order
) -> str:  # The navigation's markdown ("" when the post has neither)
    """The post navigation: the series position, then the collections line, as simple callouts."""
    out: List[str] = []
    if series:
        lines = [f"**Part {series['part']} of {series['total']}** in {_md_link(series['title'], series['href'])}"]
        steps = []
        if series.get("prev"):
            steps.append("Previous: " + _md_link(series["prev"]["title"], series["prev"]["href"]))
        if series.get("next"):
            steps.append("Next: " + _md_link(series["next"]["title"], series["next"]["href"]))
        if steps:
            lines.append(" · ".join(steps))
        out.append('::: {.callout-tip .derived-nav appearance="simple" icon=false}\n'
                   + "  \n".join(lines) + "\n:::\n")
    if collections:
        label = "In the collection" if len(collections) == 1 else "In the collections"
        out.append('::: {.callout-note .derived-nav appearance="simple" icon=false}\n'
                   + label + ": " + ", ".join(_md_link(c["title"], c["href"]) for c in collections)
                   + "\n:::\n")
    return "\n".join(out)


def _post_href(
    note_id: str,
    src: str,                              # The post's source, relative to the root
    pages: Dict[str, Dict[str, Any]],      # redirect_plan's {subject: {active, superseded}}
) -> str:
    """A post's public path: its active site_path fact, else the path its source renders at."""
    page = pages.get(note_id)
    if page:
        return page["active"]
    d = posixpath.dirname(src)
    return "/" + (d + "/" if posixpath.basename(src).startswith("index.") else src.rsplit(".", 1)[0] + ".html")


async def derived_plan(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    planned_pages: List[Dict[str, Any]],  # page_plan's pages (each with `listed`: the note ids it lists, in order; `href`; `title`)
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    inputs: List[str],                  # The profile's input documents (absolute, from `quarto inspect`)
) -> Dict[str, Any]:  # {posts: {source: {drop, nav}}, counts, errors}
    """Plan every rendered post's drops and navigation. A derived block with no link target
    cannot be named to the filter, so it refuses rather than stays silently."""
    root = Path(website_root).resolve()
    rendered = {Path(d).resolve().relative_to(root).as_posix() for d in inputs}
    notes = {str(F.nid(n)): n for n in await F.load_label(gx, DevNodeKinds.NOTE)}
    src_of: Dict[str, str] = {}
    for nid, n in notes.items():
        raw = F.prop(n, "path")
        p = Path(str(raw)).resolve() if raw else None
        if p is not None and p.is_relative_to(root) and p.relative_to(root).as_posix() in rendered:
            src_of[nid] = p.relative_to(root).as_posix()
    posts: Dict[str, Dict[str, Any]] = {}
    errors: List[Dict[str, Any]] = []
    sections = await F.load_label_where(gx, DevNodeKinds.SECTION,
                                        [PropertyPredicate("block_role", "not_null")])
    for s in sorted(sections, key=lambda s: (str(F.prop(s, "note_id")), int(F.prop(s, "order") or 0))):
        role, nid = str(F.prop(s, "block_role") or ""), str(F.prop(s, "note_id") or "")
        if nid not in src_of or role not in ROLES:
            continue
        text = str(F.prop(s, "raw") or F.prop(s, "text") or "")
        if role == CHROME_INCLUDE:
            # Named by the partial it includes: the filter parses that file for the blocks it expands to
            inc = include_target(text)
            if not inc or not (root / inc.lstrip("/")).is_file():
                errors.append({"kind": "derived-include", "source": src_of[nid], "include": inc,
                               "section": str(F.nid(s)),
                               "why": "a chrome include names no partial in the site project"})
                continue
            drop = {"role": role, "include": inc}
        else:
            links = block_link_targets(text)
            if not links:
                errors.append({"kind": "derived-unnamed", "source": src_of[nid], "role": role,
                               "section": str(F.nid(s)),
                               "why": "a derived block with no link target cannot be named to the render filter"})
                continue
            drop = {"role": role, "links": links}
        if role == HAND_TOC and _RULE_LINE_RE.search(text):
            drop["rule"] = True
        posts.setdefault(src_of[nid], {"drop": [], "nav": "", "end": ""})["drop"].append(drop)
    series_nav: Dict[str, Dict[str, Any]] = {}
    collections: Dict[str, List[Dict[str, str]]] = {}
    for page in planned_pages:
        members = [m for m in page["listed"] if m in src_of]
        if page["kind"] == DevNodeKinds.SERIES:
            for i, m in enumerate(members):
                step = lambda j: ({"title": str(F.prop(notes[members[j]], "title") or ""),
                                   "href": _post_href(members[j], src_of[members[j]], pages)}
                                  if 0 <= j < len(members) else None)
                series_nav[m] = {"title": page["title"], "href": page["href"], "part": i + 1,
                                 "total": len(members), "prev": step(i - 1), "next": step(i + 1)}
        else:
            for m in members:
                collections.setdefault(m, []).append({"title": page["title"], "href": page["href"]})
    for nid in set(series_nav) | set(collections):
        nav = render_nav(series_nav.get(nid), collections.get(nid, []))
        posts.setdefault(src_of[nid], {"drop": [], "nav": "", "end": ""})["nav"] = nav
    # The end matter: the author strip replacing the chrome includes (design 39c51c15 (5))
    # — its copy is required only when a rendered post carries one
    from .postpage import (POST_KINDS, end_plan, license_facts, load_strip_copy, offered_backing,
                           pitch_target, post_licenses, related_context, related_posts)
    from .purenotes import note_types
    types = await note_types(gx)
    ends: Dict[str, Any] = {"ends": {}, "counts": {}}
    post_lic: Dict[str, Dict[str, Any]] = {}
    if any((types.get(n) or {}).get("kind") in POST_KINDS for n in src_of):
        strip = load_strip_copy(website_root)
        errors += strip["errors"]
        if not strip["errors"]:
            # Related posts, among the posts this profile renders (39c51c15 (4))
            ctx = await related_context(gx)
            cands = {n: {"title": str(F.prop(notes[n], "title") or ""), "href": _post_href(n, s, pages),
                         "kind": (types.get(n) or {}).get("kind"),
                         "date": (F.prop(notes[n], "metadata") or {}).get("date")}
                     for n, s in src_of.items() if (types.get(n) or {}).get("kind") in POST_KINDS}
            related = {n: related_posts(n, cands, ctx) for n in cands}
            # Every post states its licenses: its own override, else its class's (39c51c15 (6))
            lic = await license_facts(gx)
            for n in cands:
                r = post_licenses(n, (types.get(n) or {}).get("type") or "", lic)
                if "error" in r:
                    errors.append({"kind": "post-license", "source": src_of[n], "why": r["error"]})
                else:
                    post_lic[n] = r
            ends = end_plan(strip["copy"], src_of, types, await offered_backing(gx),
                            pitch_target(planned_pages), related, post_lic)
    for nid, md in ends["ends"].items():
        posts.setdefault(src_of[nid], {"drop": [], "nav": "", "end": ""})["end"] = md
    # The header (39c51c15 (2)): the kind label and the dated facts, as metadata the filter sets
    from .postpage import header_facts, header_meta
    facts = await header_facts(gx)
    heads = 0
    for nid, src in src_of.items():
        t = types.get(nid) or {}
        if t.get("kind") not in POST_KINDS:
            continue
        meta = header_meta(t["kind"], t.get("origin", ""), F.prop(notes[nid], "metadata") or {},
                           facts.get(nid, {}))
        if meta["set"] or meta["unset"]:
            posts.setdefault(src, {"drop": [], "nav": "", "end": ""})["meta"] = meta
            heads += 1
    ends["counts"]["headers"] = heads
    # The footer, derived from the PUBLIC posts this profile renders (39c51c15 (6)): an archive
    # post's own dates, a born post's publication, every revision
    footer: Optional[Dict[str, Any]] = None
    if post_lic:
        from .postpage import load_holder, site_footer
        from .sitepages import parse_date
        dated, public_lic = [], []
        for n in post_lic:
            t, md, f = types.get(n) or {}, F.prop(notes[n], "metadata") or {}, facts.get(n, {})
            own = parse_date(md.get("date")) if t.get("origin") != "born" else None
            published = f.get("published") or (own.isoformat() if own else "")
            if not published:
                continue   # a draft: not public
            mod = parse_date(md.get("date-modified")) if t.get("origin") != "born" else None
            dated.append({"published": published,
                          "updated": max(v for v in (f.get("revised") or "", mod.isoformat() if mod else "", published) if v)})
            public_lic.append(post_lic[n])
        holder = load_holder(website_root)
        errors += holder["errors"]
        if not holder["errors"] and dated:
            footer = site_footer(holder["holder"], dated, public_lic)
            ends["counts"]["footer_years"] = footer["website"]["page-footer"]["center"][0]["text"]
    counts = {"posts": len(posts), "series_nav": len(series_nav), "collections": len(collections),
              **ends["counts"]}
    for role in ROLES:
        counts[role] = sum(1 for p in posts.values() for d in p["drop"] if d["role"] == role)
    return {"posts": dict(sorted(posts.items())), "counts": counts, "errors": errors, "footer": footer}


def write_derived(
    website_root: str,         # The site project root
    plan: Dict[str, Any],      # derived_plan's report
) -> Dict[str, Any]:  # {written: [file names], report_cleared}
    """Write the data file and the filter (only what changed) and clear the report."""
    d = Path(website_root) / DERIVED_DIR
    d.mkdir(exist_ok=True)
    written = []
    for name, text in ((DATA_FILE, json.dumps(plan["posts"], indent=1, ensure_ascii=False) + "\n"),
                       (FILTER_FILE, LUA_FILTER)):
        p = d / name
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")
            written.append(name)
    # The generated footer (39c51c15 (6)), a metadata-files entry of the site config; none, none written
    from .postpage import FOOTER_FILE
    foot = d / FOOTER_FILE
    if plan.get("footer"):
        text = "# GENERATED by site-build from the notes graph (design 39c51c15 (6)): do not edit.\n" + \
            yaml.safe_dump(plan["footer"], sort_keys=False, allow_unicode=True, width=10_000)
        if not foot.exists() or foot.read_text(encoding="utf-8") != text:
            foot.write_text(text, encoding="utf-8")
            written.append(FOOTER_FILE)
    elif foot.exists():
        foot.unlink()
    report = d / REPORT_FILE
    cleared = report.exists()
    report.unlink(missing_ok=True)
    return {"written": written, "report_cleared": cleared}


def check_derived(
    website_root: str,     # The site project root
    plan: Dict[str, Any],  # derived_plan's report
) -> Dict[str, Any]:  # {reported, errors}
    """After the render: every planned post reported, each named block dropped exactly once, and
    its navigation inserted. A post the filter never reported fails (the filter did not run)."""
    report = Path(website_root) / DERIVED_DIR / REPORT_FILE
    rows: Dict[str, List[Dict[str, Any]]] = {}
    if report.exists():
        for line in report.read_text(encoding="utf-8").splitlines():
            if line.strip():
                r = json.loads(line)
                rows.setdefault(r["input"], []).append(r)
    errors: List[Dict[str, Any]] = []
    for src, entry in plan["posts"].items():
        got = rows.get(src)
        if not got:
            errors.append({"kind": "derived-unreported", "source": src,
                           "why": "the render filter never reported this post (it did not run)"})
            continue
        last = got[-1]
        for want, have in zip(entry["drop"], last["dropped"]):
            if have["count"] != 1:
                errors.append({"kind": "derived-drop", "source": src, "role": want["role"],
                               "count": have["count"],
                               "why": "a named derived block was not dropped exactly once"})
        if bool(entry["nav"]) != bool(last["nav"]):
            errors.append({"kind": "derived-nav", "source": src,
                           "why": "the post's navigation was not inserted"})
        if bool(entry.get("end")) != bool(last.get("end")):
            errors.append({"kind": "derived-end", "source": src,
                           "why": "the post's end matter (the author strip) was not inserted"})
    return {"reported": len(rows), "errors": errors}


def check_end_placement(
    output_dir: str,       # The profile's output dir
    plan: Dict[str, Any],  # derived_plan's report
) -> Dict[str, Any]:  # {checked, errors}
    """After the render: every post's end matter sits inside the page's <main>. A source that
    leaves an element open can push the blocks after it out of the content (ruling ea676ba0:
    such a defect is fixed at the source), so the build names the post instead of shipping it."""
    out = Path(output_dir)
    checked = 0
    errors: List[Dict[str, Any]] = []
    for src, entry in plan["posts"].items():
        page = out / (posixpath.splitext(src)[0] + ".html")
        if not entry.get("end") or not page.exists():
            continue
        checked += 1
        html = page.read_text(encoding="utf-8")
        at, main_end = html.find("author-strip"), html.find("</main>")
        if at < 0 or main_end < 0 or at > main_end:
            errors.append({"kind": "derived-end-placement", "source": src,
                           "why": "the post's end matter renders outside <main> (an element its source leaves open?)"})
    return {"checked": checked, "errors": errors}
