"""The site's PROJECTED pages: every series page from its Series, every topic page from its Lens
(design e240183f under the redesign build 8079ae0f; 13753cbf (2), 903bc108 (2)).

A projected page's source file is build output, never committed. Its LOCATION is derived from
the node's active `site_path` (`/series/tutorials/x.html` -> `series/tutorials/x.qmd`, the
born-post rule of 98293e72 applied to pages), so no URL moves; its FRONT MATTER comes from the
node's data through one template per node kind:

- a Series lists its members in their AUTHORED order (IN_SERIES + `after`, `series_order`),
  each numbered;
- a Lens lists the notes it selects, sorted by the Lens's own `view.sort` (sitelisting.sort_rows,
  the one sorter); a Lens whose view groups by `series` lists a member THROUGH its Series page,
  one entry per project (the logs index, design 7657c4a5);
- a Lens whose view layout is `coverage-matrix` projects the Tutorials page instead
  (tutorialspage.py, design 7f200ecb): the grid, the learning paths, the tutorials by task;
- a Lens whose view layout is `library` projects the Library index instead, with a work page
  for every work with units (librarypage.py, design 638b7b85);
- a Lens whose view layout is `category-listing` projects the site's CATEGORY LISTING (design
  ce17606b (3)), the page every chip links into: every public post, its chips filtering it in
  place, and the feed; under the public profile a public post it leaves out refuses the page;
- a Lens whose view layout is `category-index` projects the CATEGORY INDEX and every CATEGORY
  PAGE (categorypages.py, design a62f2499): a page per facet entry that earns one, a redirect stub
  for every entry below the threshold. Planned FIRST, since every chip on every other page links
  the category's page where one exists;
- a Lens whose view layout is `home` projects the HOME PAGE (homepage.py, design e55201e2 and
  amendments 5c3c2662 / 8b4f15d0): a map of the index pages and the category listing its
  selection names, planned LAST, since it reads every other planned page. Each index page states
  its HUBS -- the projected pages it links, in the order it shows them -- for the map to read;
  the category listing's entry reads the posts it lists.

A Series page and a work page are ORDERED collections (`sequence` on the planned entry): the
post navigation, JSON-LD isPartOf and llms.txt walk them in order (638b7b85 (5)).

A RETIRED source (publish_state retired, design amendment e916a4b9) is never listed, under
any profile.

Nothing per-page lives in a template: title, description, image, categories (a Series page's are
the ones MORE THAN HALF of its listed members carry, design ce17606b (4)) and dates come from the
graph, and `date-modified` is DERIVED as the newest updated date
(a literal `date-modified`, else `date`) among the members the page lists. The public profile
lists only public members (a publish_state of `published`, or none on a Note of an archive
type, design amendment c64e07e7); staging lists the drafts too, and a member neither rule
decides refuses the page.

Every listing is the PROJECTED LISTING (sitelisting.py, design 0efb5497 + amendment e66296bd):
markup in the page's body, no Quarto listing key. A listed item's chips are the graph's
(categories.py), never its front matter's (design ce17606b (3)). The category listing and every
category page carry a feed, written after the render from the rendered posts (sitefeeds.py).

Every generated page opens its front matter with the GENERATED marker. A projection removes a
marked page it no longer plans (a moved or retired page) and REFUSES to write over an unmarked
file (a hand page still in the tree) — the build says so, it never overwrites source."""

import os
import posixpath
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml
from cjm_dev_graph_schema import predicates as P
from cjm_dev_graph_schema.vocab import DevNodeKinds

from . import factlayer as F
from .aboutpage import LAYOUT as ABOUT_LAYOUT, plan_about_page
from .archive import is_retired
from .homepage import LAYOUT as HOME_LAYOUT, plan_home_page
from .lens import apply_lens, LENS_LABEL
from .librarypage import LAYOUT as LIBRARY_LAYOUT, plan_library_pages
from .runtime import GraphHandle
from .series import series_order
from .sitelisting import (chip_hrefs, feed_header, feed_plan, listing_kinds, listing_script,
                          load_site_title, note_item, page_item, render_listing, SCRIPT_FILE,
                          sort_rows, title_html)
from .tutorialspage import LAYOUT as MATRIX_LAYOUT, plan_matrix_page

GENERATED = "# GENERATED by site-build from the notes graph (design e240183f): do not edit, it is overwritten"

GROUP_SERIES = "series"   # view.group_by: a member listed through its Series page (design 7657c4a5 (1))
CATEGORY_LAYOUT = "category-listing"   # The site's category listing (design ce17606b (3))
# The site listing template of a7224060, retired with Quarto's listings (design 0efb5497): a
# projection removes the copy an earlier build left
RETIRED_TEMPLATE = "_derived/listing-default.ejs.md"

# Front-matter date forms the archive carries (ISO with or without padding, M/D/YYYY, M-D-YYYY)
_DATE_FORMATS = ("%Y-%m-%d", "%m/%d/%Y", "%m-%d-%Y")
# Output and cache trees a projection never scans for stale pages
_SKIP_DIRS = ("_site", "_site-staging", ".quarto", "site_libs", ".git", "_freeze")


def page_source(
    path: str,  # A page's site path ("/series/tutorials/x.html")
) -> Optional[str]:  # Its source file relative to the root ("series/tutorials/x.qmd"); None = not a page path
    """The source a page's output is rendered from: Quarto's output file with `.qmd`."""
    from .site import output_href
    out = output_href(path)
    return out[:-len(".html")] + ".qmd" if out.endswith(".html") else None


def parse_date(
    value: Any,  # A front-matter date (a string in any archive form, or a YAML-parsed date)
) -> Optional[date]:  # The day, or None (absent, `last-modified`, unparseable)
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(str(value).strip(), fmt).date()
        except ValueError:
            continue
    return None


def member_updated(
    note: Any,  # A Note node
) -> Optional[date]:  # Its updated date: a literal date-modified, else its date
    """`last-modified` is a file mtime (a checkout time, not an edit), so it never counts."""
    md = F.prop(note, "metadata") or {}
    for key in ("date-modified", "date"):
        d = parse_date(md.get(key))
        if d is not None:
            return d
    return None


def is_public(
    note_id: str,                          # A Note id
    states: Dict[str, List[str]],          # note_publish_states' map (deliverables only)
    types: Dict[str, Dict[str, Any]],      # note_types' map (typed Notes only)
) -> Optional[bool]:  # True / False, or None = undecidable (neither a state nor an archive type)
    """A publish_state decides (public only when `published`); with none, a Note of an ARCHIVE
    type is public as authored (design amendment c64e07e7). A Note with neither is undecidable:
    the caller reports it, never guesses (a wrong exclusion hides content, 6752db0a (9))."""
    vals = states.get(note_id)
    if vals is not None:
        return vals == [P.PUBLISH_PUBLISHED]
    if (types.get(note_id) or {}).get("origin") == P.ORIGIN_ARCHIVE:
        return True
    return None


def render_page(
    front: Dict[str, Any],  # The page's front matter, in order
    body: str = "",         # The page's body, markdown ("" = none)
) -> str:  # The page file: the GENERATED marker, the front matter, the body
    head = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, width=10_000)
    return f"---\n{GENERATED}\n{head}---\n" + (f"\n{body.strip()}\n" if body.strip() else "")


def is_generated(
    path: Path,  # A source file
) -> bool:
    try:
        with path.open(encoding="utf-8") as f:
            return f.readline().rstrip("\n") == "---" and f.readline().rstrip("\n") == GENERATED
    except (OSError, UnicodeDecodeError):
        return False


def _listed(
    members: List[Any],        # Member Note nodes, in listing order
    page_src: str,             # The page's source, relative to the root
    root: Path,                # The site project root (resolved)
    profile: str,              # public | staging
    states: Dict[str, List[str]],
    types: Dict[str, Dict[str, Any]],
    drafts: Optional[Path],    # The drafts tree (resolved), never listed on the public profile
    subject: str,              # The page's node id (error rows name it)
    post_cats: Optional[Dict[str, List[str]]] = None,  # categories.load_post_categories' posts (None = none read)
) -> Dict[str, Any]:  # {contents, ids, updated, cats, errors}
    """The members a page lists under the profile, as contents paths relative to the page (and
    their note ids, in the same order: the post navigation's members, 253ac996 (3)), and the
    categories each listed source carries -- the graph's, never its front matter's (design
    ce17606b (1))."""
    contents: List[str] = []
    ids: List[str] = []
    cats: Dict[str, List[str]] = {}
    dates: List[date] = []
    errors: List[Dict[str, Any]] = []
    for n in members:
        nid = str(F.nid(n))
        if is_retired(nid, states):
            continue   # a retired source is never listed, under any profile (e916a4b9 (3))
        public = is_public(nid, states, types)
        if public is None:
            errors.append({"kind": "member-undecidable", "subject": subject, "member": nid,
                           "slug": F.prop(n, "slug"),
                           "why": "a listed member has neither a publish_state nor an archive type"})
            continue
        if profile == "public" and not public:
            continue
        raw = F.prop(n, "path")
        src = Path(str(raw)).resolve() if raw else None
        if src is None or not src.is_relative_to(root):
            errors.append({"kind": "member-path", "subject": subject, "member": nid, "path": raw,
                           "why": "a listed member has no source inside the site project"})
            continue
        if profile == "public" and drafts is not None and src.is_relative_to(drafts):
            errors.append({"kind": "member-draft", "subject": subject, "member": nid,
                           "why": "a public page would list a file in the drafts tree"})
            continue
        contents.append(posixpath.relpath(src.relative_to(root).as_posix(),
                                          posixpath.dirname(page_src) or "."))
        ids.append(nid)
        cats[src.relative_to(root).as_posix()] = list((post_cats or {}).get(nid) or [])
        d = member_updated(n)
        if d is not None:
            dates.append(d)
    return {"contents": contents, "ids": ids, "updated": max(dates).isoformat() if dates else None,
            "cats": cats, "errors": errors}


def _front(
    node: Any,                       # The Series or Lens node
    updated: Optional[str],          # The derived date-modified
    categories: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """A listing page's front matter: the node's title, description and dates, and the categories
    a Series page carries. The category listing is titled like every other listing (amendment
    e66296bd (5))."""
    front: Dict[str, Any] = {"title": F.prop(node, "title") or F.prop(node, "key")}
    for key in ("description", "date"):
        if F.prop(node, key):
            front[key] = F.prop(node, key)
    if updated:
        front["date-modified"] = updated
    if categories:
        front["categories"] = categories
    if F.prop(node, "image"):
        front["image"] = F.prop(node, "image")
    return front


def check_category_listing(
    planned: List[Dict[str, Any]],      # Every planned page
    listing_href: str,                  # The category listing the site config names ("" = none)
    profile: str,                       # public | staging
    states: Dict[str, List[str]],
    types: Dict[str, Dict[str, Any]],
) -> List[Dict[str, Any]]:  # Error rows
    """The category listing a Lens projects (design ce17606b (3)) is the page every chip links
    into: one such page, at the path the site config names, and under the public profile it lists
    EVERY public post -- a post it left out would be reachable from no chip (a wrong exclusion
    hides content, 6752db0a (9))."""
    pages = [p for p in planned if p.get("layout") == CATEGORY_LAYOUT]
    errors: List[Dict[str, Any]] = []
    if len(pages) > 1:
        errors.append({"kind": "category-listing", "subjects": [p["subject"] for p in pages],
                       "why": "two Lenses project the category listing"})
    for p in pages:
        if listing_href and p["href"] != listing_href:
            errors.append({"kind": "category-listing", "subject": p["subject"], "href": p["href"],
                           "named": listing_href,
                           "why": "a category-listing Lens lands off the page the site config names"})
        if profile != "public":
            continue
        missing = unlisted_posts(set(p["listed"]), states, types)
        if missing:
            errors.append({"kind": "category-listing-incomplete", "subject": p["subject"], "missing": missing,
                           "why": "the category listing leaves out public posts; its selection must cover every post kind"})
    return errors


def unlisted_posts(
    listed: set,                        # The note ids a page lists
    states: Dict[str, List[str]],
    types: Dict[str, Dict[str, Any]],
) -> List[str]:  # The public, unretired posts it leaves out, sorted
    """The posts a page meant to cover every post leaves out (the category listing, ce17606b (3);
    the category index, whose counts would read short, a62f2499 (5))."""
    from .postpage import POST_KINDS
    return sorted(n for n, t in types.items() if t.get("kind") in POST_KINDS and n not in listed
                  and not is_retired(n, states) and is_public(n, states, types))


async def page_plan(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    profile: str,                       # public | staging
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    drafts_dir: Optional[str] = "drafts",  # The drafts tree relative to the root
) -> Dict[str, Any]:  # {pages: [{source, kind, key, subject, members, text}], unpaged, errors}
    """Plan every projected page: a Series or Lens with an active site_path gets one; a broken
    series chain, a truncated Lens selection, or two nodes landing on one file refuse."""
    from .purenotes import note_publish_states, note_types
    root = Path(website_root).resolve()
    drafts = (root / drafts_dir).resolve() if drafts_dir else None
    states = await note_publish_states(gx)
    types = await note_types(gx)
    series = await F.load_label(gx, DevNodeKinds.SERIES)
    lenses = await F.load_label(gx, LENS_LABEL)
    from .categories import load_post_categories, majority
    chips = await load_post_categories(gx)   # every post's categories, the graph's (design ce17606b (1))
    planned: List[Dict[str, Any]] = []
    unpaged: List[str] = []
    from .postpage import load_category_listing
    # where every chip links (design a7224060); the listing may be a page this build projects (ce17606b (3))
    category = load_category_listing(website_root, projected={page_source(p["active"]) for p in pages.values()
                                                              if p.get("active")})
    errors: List[Dict[str, Any]] = list(category["errors"]) + list(chips["errors"])
    site_title = load_site_title(website_root)   # a feed's title, as the page head names it
    # The category pages first (design a62f2499): every other page's chips link them
    from .categorypages import INDEX_LAYOUT, plan_category_pages
    index_lenses = [n for n in lenses if (F.prop(n, "view") or {}).get("layout") == INDEX_LAYOUT]
    cats_plan = await plan_category_pages(gx, index_lenses, pages, root, profile, states, types, drafts,
                                          chips, category["href"], site_title=site_title)
    errors += cats_plan["errors"]
    planned += cats_plan["pages"]
    links = cats_plan["links"]   # chip -> its category page's path
    matrix_pages: List[Any] = []   # coverage-matrix Lenses, planned after every collection page
    library_pages: List[Any] = []  # the library Lens, planned after them all (its topic line reads them)
    home_pages: List[Any] = []     # the home Lens, planned last (its map reads every index page)
    about_pages: List[Any] = []    # the About Lens, planned after them (its hand-off reads the planned pages)
    for kind, nodes in ((DevNodeKinds.SERIES, series), (LENS_LABEL, lenses)):
        for node in sorted(nodes, key=lambda n: str(F.prop(n, "key") or "")):
            sid, key = str(F.nid(node)), str(F.prop(node, "key") or "")
            if any(node is n for n in index_lenses):
                continue   # planned above with the category pages
            page = pages.get(sid)
            if page is None:
                unpaged.append(f"{kind}:{key}")
                continue
            src = page_source(page["active"])
            if src is None:
                errors.append({"kind": "page-path", "subject": sid, "path": page["active"],
                               "why": "the page's site_path names no page file"})
                continue
            if kind == DevNodeKinds.SERIES:
                order = await series_order(gx, key)
                if order.get("contradictions"):
                    errors.append({"kind": "series-order", "subject": sid, "key": key,
                                   "contradictions": order["contradictions"],
                                   "why": "the series' authored order is broken; the build never guesses one"})
                    continue
                members = list((await F.load_nodes(gx, [m["id"] for m in order["members"]])).values())
                by_id = {str(F.nid(n)): n for n in members}
                members = [by_id[m["id"]] for m in order["members"] if m["id"] in by_id]
                terms, cats, group, layout = [], None, None, None
            else:
                applied = await apply_lens(gx, key)
                if applied.get("error") or applied.get("truncated"):
                    errors.append({"kind": "lens", "subject": sid, "key": key,
                                   "why": applied.get("error") or "the Lens selection was truncated; a page would silently drop members"})
                    continue
                members = [n for n in applied["nodes"] if n.get("label") == DevNodeKinds.NOTE]
                if (applied.get("view") or {}).get("layout") == MATRIX_LAYOUT:
                    # The Tutorials page (design 7f200ecb): its learning paths are read off the
                    # other planned pages, so it is planned after all of them
                    matrix_pages.append((node, members, {"source": src, "href": page["active"]}))
                    continue
                if (applied.get("view") or {}).get("layout") == LIBRARY_LAYOUT:
                    # The Library index (design 638b7b85): its work pages are planned with it
                    library_pages.append((node, {"source": src, "href": page["active"]}))
                    continue
                if (applied.get("view") or {}).get("layout") == HOME_LAYOUT:
                    # The home page (design e55201e2): a map of the other index pages, planned last
                    home_pages.append((node, {"source": src, "href": page["active"]}))
                    continue
                if (applied.get("view") or {}).get("layout") == ABOUT_LAYOUT:
                    # The About page (design amendment 2364f215): the author's identity and background
                    about_pages.append((node, {"source": src, "href": page["active"]}))
                    continue
                layout = (applied.get("view") or {}).get("layout")
                terms, cats = list((applied.get("view") or {}).get("sort") or []), None
                group = (applied.get("view") or {}).get("group_by")
                if group not in (None, GROUP_SERIES):
                    errors.append({"kind": "lens-group", "subject": sid, "key": key, "group_by": group,
                                   "why": "a site page groups only by series (7657c4a5 (1)); the build never guesses another grouping"})
                    continue
            listed = _listed(members, src, root, profile, states, types, drafts, sid, post_cats=chips["posts"])
            errors += listed["errors"]
            if kind == DevNodeKinds.SERIES:   # what most of the series is about (design ce17606b (4))
                cats = majority([chips["posts"].get(i, []) for i in listed["ids"]], chips["rank"])
            # Every listed post as the projected listing shows it (design 0efb5497)
            by_id = {str(F.nid(n)): n for n in members}
            srcs = {i: posixpath.normpath(posixpath.join(posixpath.dirname(src), c))
                    for i, c in zip(listed["ids"], listed["contents"])}
            items = [note_item(by_id[i], srcs[i], src, chips["posts"].get(i, [])) for i in listed["ids"]]
            hubs: List[Dict[str, str]] = []   # the projected pages a Lens page links (5c3c2662 (5))
            if group == GROUP_SERIES:   # one entry per paged Series (design 7657c4a5 (1))
                grouped = group_through_series(listed["ids"], listed["contents"], planned, src, sid)
                errors += grouped["errors"]
                by_rel = dict(zip(listed["contents"], items))
                series_rel = {posixpath.relpath(p["source"], posixpath.dirname(src) or "."): p for p in grouped["series"]}
                items = [page_item(series_rel[e], src) if e in series_rel else by_rel[e] for e in grouped["contents"]]
            if terms:   # the Lens's own order; a Series keeps its authored one
                got = sort_rows(items, terms)
                if got.get("error"):
                    errors.append({"kind": "lens-sort", "subject": sid, "key": key, "why": got["error"]})
                items = got.get("rows") or items
            if group == GROUP_SERIES:   # the Series pages it links, in the order the listing shows them
                paged = {p["source"] for p in planned if p.get("sequence")}
                hubs = [{"title": it["title"], "source": it["source"]} for it in items if it["source"] in paged]
            in_place = layout == CATEGORY_LAYOUT   # the site's category listing (design ce17606b (3))
            hrefs = chip_hrefs(sorted({c for it in items for c in it["categories"]}), category["href"], links,
                               in_place=in_place)
            body = render_listing(items, src, kinds=listing_kinds(items, chips["kinds"], chips["rank"]), hrefs=hrefs,
                                  in_place=in_place, numbered=kind == DevNodeKinds.SERIES,
                                  titles=title_html([it["title"] for it in items]),
                                  noun="parts" if kind == DevNodeKinds.SERIES else
                                  "entries" if group == GROUP_SERIES else "posts")
            front = _front(node, listed["updated"], cats)
            feed = None
            if in_place:   # the category listing's feed (0efb5497 (3b)): every post it lists, in its order
                of = {s: i for i, s in srcs.items()}
                feed = feed_plan(src, str(F.prop(node, "description") or ""),
                                 [(by_id[of[it["source"]]], it["source"], it["categories"]) for it in items])
                front.update(feed_header(posixpath.basename(feed["xml"]), site_title))
            text = render_page(front, body=body)
            planned.append({"source": src, "kind": kind, "key": key, "subject": sid, "categories": cats or [],
                            "members": len(listed["contents"]), "updated": listed["updated"],
                            "listed": listed["ids"], "href": page["active"],
                            "sequence": kind == DevNodeKinds.SERIES,
                            "title": str(F.prop(node, "title") or key),
                            "description": str(F.prop(node, "description") or ""),
                            "date": F.prop(node, "date"),
                            **({"layout": layout} if layout == CATEGORY_LAYOUT else {}),
                            **({"feed": feed} if feed else {}),
                            **({} if kind == DevNodeKinds.SERIES or layout == CATEGORY_LAYOUT else {"hubs": hubs}),
                            "text": text})
    for node, members, page in matrix_pages:
        got = await plan_matrix_page(gx, node, members, page, root, profile, states, types, drafts,
                                     list(planned), category["href"], category_pages=links, chips=chips)
        errors += got.get("errors", [])
        if got.get("page"):
            planned.append(got["page"])
    for node, page in library_pages:
        got = await plan_library_pages(gx, node, page, pages, root, profile, states, types, drafts,
                                       list(planned))
        errors += got.get("errors", [])
        planned += got.get("pages", [])
    for node, page in home_pages:
        got = await plan_home_page(gx, node, page, website_root, root, profile, states, types, drafts,
                                   list(planned))
        errors += got.get("errors", [])
        if got.get("page"):
            planned.append(got["page"])
    for node, page in about_pages:
        got = await plan_about_page(gx, node, page, website_root, profile, list(planned))
        errors += got.get("errors", [])
        if got.get("page"):
            planned.append(got["page"])
    errors += check_category_listing(planned, category["href"], profile, states, types)
    seen: Dict[str, str] = {}
    for p in planned:
        if p["source"] in seen:
            errors.append({"kind": "page-collision", "source": p["source"],
                           "subjects": [seen[p["source"]], p["subject"]],
                           "why": "two nodes' site_paths land on one page file"})
        seen[p["source"]] = p["subject"]
    return {"pages": planned, "unpaged": unpaged, "category_listing": category["href"],
            "stubs": cats_plan["stubs"], "category_pages": links, "undescribed": cats_plan["undescribed"],
            "stale_descriptions": cats_plan["stale_descriptions"],
            "errors": errors}


def _generated_files(
    root: Path,  # The site project root (resolved)
) -> List[str]:  # Every marked page in the source tree, relative to the root
    out = []
    for p in root.rglob("*.qmd"):
        rel = p.relative_to(root)
        if any(part in _SKIP_DIRS for part in rel.parts[:-1]):
            continue
        if is_generated(p):
            out.append(rel.as_posix())
    return sorted(out)


async def project_pages(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    profile: str,                       # public | staging
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    *,
    drafts_dir: Optional[str] = "drafts",
    write: bool = True,                 # False = plan and check only
) -> Dict[str, Any]:  # {planned, written, unchanged, removed, unpaged, sources, plan, errors}
    """Write the planned pages into the source tree (only those whose text changed), remove
    the marked pages no longer planned, and refuse the whole write when a planned page would
    land on an unmarked file. The category stubs (a62f2499 (3)) ride the report for the
    redirect projection."""
    root = Path(website_root).resolve()
    plan = await page_plan(gx, website_root, profile, pages, drafts_dir)
    errors = list(plan["errors"])
    for p in plan["pages"]:
        dest = root / p["source"]
        if dest.exists() and not is_generated(dest):
            errors.append({"kind": "page-over-source", "source": p["source"], "subject": p["subject"],
                           "why": "a file not generated by the build sits where a projected page lands"})
    rep: Dict[str, Any] = {"planned": len(plan["pages"]), "written": 0, "unchanged": 0, "removed": [],
                           "unpaged": plan["unpaged"], "sources": [p["source"] for p in plan["pages"]],
                           "category_listing": plan.get("category_listing") or "", "plan": plan["pages"],
                           "stubs": plan.get("stubs") or [], "undescribed": plan.get("undescribed") or [],
                           "stale_descriptions": plan.get("stale_descriptions") or []}
    if errors or not write:
        return {**rep, "errors": errors}
    wanted = {p["source"] for p in plan["pages"]}
    for rel in _generated_files(root):
        if rel not in wanted:
            (root / rel).unlink()
            rep["removed"].append(rel)
    script = root / SCRIPT_FILE   # the projected listing's site script (design 0efb5497)
    if not script.exists() or script.read_text(encoding="utf-8") != listing_script():
        script.parent.mkdir(parents=True, exist_ok=True)
        script.write_text(listing_script(), encoding="utf-8")
    (root / RETIRED_TEMPLATE).unlink(missing_ok=True)
    for p in plan["pages"]:
        dest = root / p["source"]
        if dest.exists() and dest.read_text(encoding="utf-8") == p["text"]:
            rep["unchanged"] += 1
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(p["text"], encoding="utf-8")
            rep["written"] += 1
        _stamp(dest, p["updated"])
    return {**rep, "errors": errors}


def _stamp(
    dest: Path,              # A projected page file
    updated: Optional[str],  # Its derived date-modified (ISO day), or None
) -> None:
    """Set the page file's mtime to its derived date-modified (midnight UTC). Quarto reads a
    page's file mtime for the sitemap's lastmod and the listings' file-modified key; a generated
    file's mtime would otherwise be whenever a build last wrote it (a profile switch rewrites the
    pages whose draft lists differ), so the derived date is what those fields carry."""
    if not updated:
        return
    ts = datetime.strptime(updated, "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp()
    os.utime(dest, (ts, ts))


def check_page_outputs(
    output_dir: str,     # The profile's output dir
    sources: List[str],  # The projected pages' sources (relative)
) -> List[Dict[str, Any]]:  # Error rows: a projected page the render did not produce
    """Every Series or Lens page the build projected has its rendered page (the guard's check,
    design e240183f (1))."""
    out = Path(output_dir)
    return [{"kind": "page-missing", "source": s, "why": "a projected page did not render"}
            for s in sources if not (out / (s[:-len(".qmd")] + ".html")).exists()]


def group_through_series(
    ids: List[str],                     # The Lens page's listed members, in listing order
    contents: List[str],                # Their contents paths (relative to the page), same order
    planned: List[Dict[str, Any]],      # The pages planned so far (every Series page among them)
    page_src: str,                      # The Lens page's source, relative to the root
    subject: str,                       # The Lens node's id (error rows name it)
) -> Dict[str, Any]:  # {contents, series: [the Series pages listed, as planned], errors}
    """A Lens with view.group_by "series" lists a member THROUGH its Series page (design 7657c4a5
    (1)): one entry per paged Series, in the place of its first member, a member in no paged Series
    as itself. A member two paged Series list refuses -- the build never picks one."""
    pages: Dict[str, List[str]] = {}
    by_source: Dict[str, Dict[str, Any]] = {}
    for p in planned:
        if p.get("sequence") and p.get("kind") == DevNodeKinds.SERIES:
            by_source[p["source"]] = p
            for m in p["listed"]:
                pages.setdefault(m, []).append(p["source"])
    out: List[str] = []
    series: List[Dict[str, Any]] = []
    errors: List[Dict[str, Any]] = []
    for nid, path in zip(ids, contents):
        srcs = pages.get(nid) or []
        if len(srcs) > 1:
            errors.append({"kind": "lens-group", "subject": subject, "member": nid, "series_pages": srcs,
                           "why": "a member two paged Series list; the build never picks one to group it under"})
            continue
        entry = posixpath.relpath(srcs[0], posixpath.dirname(page_src) or ".") if srcs else path
        if entry not in out:
            out.append(entry)
            if srcs:
                series.append(by_source[srcs[0]])
    return {"contents": out, "series": series, "errors": errors}


def hub_order(
    pages: List[Dict[str, Any]],  # Planned pages a listing links ({title, source, date?, updated?})
    terms: List[str],             # The listing's sort terms ("date-modified desc", "title")
) -> Dict[str, Any]:  # {hubs: [{title, source}]} | {error}
    """The pages a listing links in the order the listing SHOWS them: its sort applied to what the
    build planned for each page, by the one sorter the listing itself uses (sitelisting.sort_rows).
    The home page reads an index's hubs in this order and never re-ranks them (amendment 5c3c2662
    (5)). A sort key the build plans no value for refuses."""
    got = sort_rows(pages, terms)
    if got.get("error"):
        return {"error": got["error"]}
    rows = got["rows"]
    return {"hubs": [{"title": str(p.get("title") or ""), "source": p["source"]} for p in rows]}
