"""The site's PROJECTED pages: every series page from its Series, every topic page from its Lens
(design e240183f under the redesign build 8079ae0f; 13753cbf (2), 903bc108 (2)).

A projected page's source file is build output, never committed. Its LOCATION is derived from
the node's active `site_path` (`/series/tutorials/x.html` -> `series/tutorials/x.qmd`, the
born-post rule of 98293e72 applied to pages), so no URL moves; its FRONT MATTER comes from the
node's data through one template per node kind:

- a Series lists its members in their AUTHORED order (IN_SERIES + `after`, `series_order`)
  as an explicit `contents` list under `sort: false`, with no sort or filter UI;
- a Lens lists the notes it selects, sorted by the Lens's own `view.sort` (handed to Quarto's
  listing sorter, the one the hand pages used), with the sort and filter UI of a filter; a Lens
  whose view groups by `series` lists a member THROUGH its Series page, one entry per project
  (the logs index, design 7657c4a5);
- a Lens whose view layout is `coverage-matrix` projects the Tutorials page instead
  (tutorialspage.py, design 7f200ecb): the grid, the learning paths, the tutorials by task;
- a Lens whose view layout is `library` projects the Library index instead, with a work page
  for every work with units (librarypage.py, design 638b7b85).

A Series page and a work page are ORDERED collections (`sequence` on the planned entry): the
post navigation, JSON-LD isPartOf and llms.txt walk them in order (638b7b85 (5)).

A RETIRED source (publish_state retired, design amendment e916a4b9) is never listed, under
any profile.

Nothing per-page lives in a template: title, description, image, categories (the Series' TAGGED
topics) and dates come from the graph, and `date-modified` is DERIVED as the newest updated date
(a literal `date-modified`, else `date`) among the members the page lists. The public profile
lists only public members (a publish_state of `published`, or none on a Note of an archive
type, design amendment c64e07e7); staging lists the drafts too, and a member neither rule
decides refuses the page.

Every generated page opens its front matter with the GENERATED marker. A projection removes a
marked page it no longer plans (a moved or retired page) and REFUSES to write over an unmarked
file (a hand page still in the tree) — the build says so, it never overwrites source."""

import os
import posixpath
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml
from cjm_context_graph_layer.ops import graph_task
from cjm_context_graph_primitives.query import EdgeQuery
from cjm_dev_graph_schema import predicates as P
from cjm_dev_graph_schema.vocab import DevNodeKinds, DevRelations

from . import factlayer as F
from .archive import is_retired
from .lens import apply_lens, LENS_LABEL
from .librarypage import LAYOUT as LIBRARY_LAYOUT, plan_library_pages
from .runtime import GraphHandle
from .series import series_order
from .tutorialspage import LAYOUT as MATRIX_LAYOUT, plan_matrix_page

GENERATED = "# GENERATED by site-build from the notes graph (design e240183f): do not edit, it is overwritten"

# One template per node kind (design e240183f (3)): listing options only, never page data.
FIELDS = ["date", "title", "reading-time", "description", "categories"]
SERIES_LISTING = {"sort": False, "type": "default", "categories": False,
                  "sort-ui": False, "filter-ui": False, "fields": FIELDS}
# A Lens page's sort and filter fields are NAMED (design a7224060): Quarto picks them by listing
# type, and the site listing template is a custom listing to it -- the default type's sort fields
# shown (title, date) and the fields it searched that an entry carries (date, title, description)
LENS_LISTING = {"type": "default", "categories": False,
                "sort-ui": ["title", "date"], "filter-ui": ["date", "title", "description"], "fields": FIELDS}
GROUP_SERIES = "series"   # view.group_by: a member listed through its Series page (design 7657c4a5 (1))
# Every projected listing renders through the SITE LISTING TEMPLATE (design a7224060): Quarto's
# default listing with each category chip a link into the category listing, every href planned by
# the build. Written into the git-ignored _derived/ beside the derived-blocks filter; each page
# names it relative to its own source (Quarto resolves a listing template against the page).
LISTING_TEMPLATE_FILE = "_derived/listing-default.ejs.md"
LISTING_TEMPLATE = r'''<%
// GENERATED by site-build from the notes graph (design a7224060): do not edit, it is overwritten.
// Quarto 1.10's default listing and item templates (listing-default.ejs.md + item-default.ejs.md)
// with ONE change: a category chip is a link into the category listing, filtered to it -- the
// build plans every href (templateParams['category-links']); a category it planned none for is a
// label. A custom template gets no `listing`, so the fields come in templateParams too, and the
// image block is left out (no projected listing shows images).
const fields = templateParams.fields || [];
const links = templateParams['category-links'] || {};
const otherFields = fields.filter(field => {
return !["title", "image", "image-alt", "date", "author", "subtitle", "description", "reading-time", "categories"].includes(field);
});
%>

::: {.list .quarto-listing-default}

<% for (const item of items) { %>

::: {.quarto-post .image-right <%= metadataAttrs(item) %>}

::: {.body}

<% if (fields.includes('title')) { %>
<h3 class="no-anchor listing-title"><a href="<%- item.path %>" class="no-external"><%= item.title %></a></h3>
<% if (fields.includes('subtitle')) { %>
<div class="listing-subtitle"><a href="<%- item.path %>" class="no-external"><%= item.subtitle %></a></div>
<% } %>
<% } %>

<% if (fields.includes('categories') && item.categories) { %>

```{=html}
<div class="listing-categories">
<% for (const category of item.categories) { %>
<% if (links[category]) { %><a class="listing-category" href="<%= links[category] %>"><%= category %></a><% } else { %><div class="listing-category"><%= category %></div><% } %>
<% } %>
</div>
```

<% } %>

<% if (fields.includes('description')) { %>

```{=html}
<div class="delink listing-description"><a href="<%- item.path %>" class="no-external">
```

<%= item.description %>

```{=html}
</a></div>
```

<% } %>

:::

::: {.metadata}

```{=html}
<a href="<%- item.path %>" class="no-external">
```

<% if (fields.includes('date') && item.date) { %>
<div class="listing-date"><%= item.date %></div>
<% } %>

<% if (fields.includes('author') && item.author) { %>
<div class="listing-author"><%= item.author %></div>
<% } %>

<% if (fields.includes('reading-time') && item['reading-time']) { %>

```{=html}
<div class="listing-reading-time"><%= item['reading-time'] %></div>
```

<% } %>

<% for (const field of otherFields) { %>
<% if (item[field] !== undefined) { %>
<div class="metadata-value listing-<%= field %>"><%= item[field] %></div>
<% } %>
<% } %>

```{=html}
</a>
```

:::

:::

<% } %>

:::
'''

# Front-matter date forms the archive carries (ISO with or without padding, M/D/YYYY, M-D-YYYY)
_DATE_FORMATS = ("%Y-%m-%d", "%m/%d/%Y", "%m-%d-%Y")
# Output and cache trees a projection never scans for stale pages
_SKIP_DIRS = ("_site", "_site-staging", ".quarto", "site_libs", ".git", "_freeze")


def page_source(
    path: str,  # A page's site path ("/series/tutorials/x.html")
) -> Optional[str]:  # Its source file relative to the root ("series/tutorials/x.qmd"); None = not a page path
    """The source a page's output is rendered from: Quarto's output file with `.qmd`."""
    from .site import output_href
    out = output_href(path)
    return out[:-len(".html")] + ".qmd" if out.endswith(".html") else None


def parse_date(
    value: Any,  # A front-matter date (a string in any archive form, or a YAML-parsed date)
) -> Optional[date]:  # The day, or None (absent, `last-modified`, unparseable)
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(str(value).strip(), fmt).date()
        except ValueError:
            continue
    return None


def member_updated(
    note: Any,  # A Note node
) -> Optional[date]:  # Its updated date: a literal date-modified, else its date
    """`last-modified` is a file mtime (a checkout time, not an edit), so it never counts."""
    md = F.prop(note, "metadata") or {}
    for key in ("date-modified", "date"):
        d = parse_date(md.get(key))
        if d is not None:
            return d
    return None


def is_public(
    note_id: str,                          # A Note id
    states: Dict[str, List[str]],          # note_publish_states' map (deliverables only)
    types: Dict[str, Dict[str, Any]],      # note_types' map (typed Notes only)
) -> Optional[bool]:  # True / False, or None = undecidable (neither a state nor an archive type)
    """A publish_state decides (public only when `published`); with none, a Note of an ARCHIVE
    type is public as authored (design amendment c64e07e7). A Note with neither is undecidable:
    the caller reports it, never guesses (a wrong exclusion hides content, 6752db0a (9))."""
    vals = states.get(note_id)
    if vals is not None:
        return vals == [P.PUBLISH_PUBLISHED]
    if (types.get(note_id) or {}).get("origin") == P.ORIGIN_ARCHIVE:
        return True
    return None


def render_page(
    front: Dict[str, Any],  # The page's front matter, in order
) -> str:  # The page file: the GENERATED marker, the front matter, no body
    body = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, width=10_000)
    return f"---\n{GENERATED}\n{body}---\n"


def is_generated(
    path: Path,  # A source file
) -> bool:
    try:
        with path.open(encoding="utf-8") as f:
            return f.readline().rstrip("\n") == "---" and f.readline().rstrip("\n") == GENERATED
    except (OSError, UnicodeDecodeError):
        return False


async def _tagged_topics(
    gx: GraphHandle,
    ids: List[str],  # Series ids
) -> Dict[str, List[str]]:  # Series id -> its topic keys, sorted
    if not ids:
        return {}
    res = await graph_task(gx.queue, gx.graph_id, "query_edges",
                           query=EdgeQuery(source_ids=ids, relation_type=DevRelations.TAGGED).to_dict())
    raw = getattr(res, "edges", None) or getattr(res, "rows", None) or []
    rows = [e.to_dict() if hasattr(e, "to_dict") else dict(e) for e in raw]
    topics = await F.load_nodes(gx, sorted({str(r["target_id"]) for r in rows}))
    out: Dict[str, List[str]] = {}
    for r in rows:
        key = F.prop(topics.get(str(r["target_id"])), "key")
        if key:
            out.setdefault(str(r["source_id"]), []).append(str(key))
    return {k: sorted(set(v)) for k, v in out.items()}


def _listed(
    members: List[Any],        # Member Note nodes, in listing order
    page_src: str,             # The page's source, relative to the root
    root: Path,                # The site project root (resolved)
    profile: str,              # public | staging
    states: Dict[str, List[str]],
    types: Dict[str, Dict[str, Any]],
    drafts: Optional[Path],    # The drafts tree (resolved), never listed on the public profile
    subject: str,              # The page's node id (error rows name it)
) -> Dict[str, Any]:  # {contents, ids, updated, cats, errors}
    """The members a page lists under the profile, as contents paths relative to the page (and
    their note ids, in the same order: the post navigation's members, 253ac996 (3)), and the
    categories each listed source carries (its chips' links, design a7224060)."""
    contents: List[str] = []
    ids: List[str] = []
    cats: Dict[str, List[str]] = {}
    dates: List[date] = []
    errors: List[Dict[str, Any]] = []
    for n in members:
        nid = str(F.nid(n))
        if is_retired(nid, states):
            continue   # a retired source is never listed, under any profile (e916a4b9 (3))
        public = is_public(nid, states, types)
        if public is None:
            errors.append({"kind": "member-undecidable", "subject": subject, "member": nid,
                           "slug": F.prop(n, "slug"),
                           "why": "a listed member has neither a publish_state nor an archive type"})
            continue
        if profile == "public" and not public:
            continue
        raw = F.prop(n, "path")
        src = Path(str(raw)).resolve() if raw else None
        if src is None or not src.is_relative_to(root):
            errors.append({"kind": "member-path", "subject": subject, "member": nid, "path": raw,
                           "why": "a listed member has no source inside the site project"})
            continue
        if profile == "public" and drafts is not None and src.is_relative_to(drafts):
            errors.append({"kind": "member-draft", "subject": subject, "member": nid,
                           "why": "a public page would list a file in the drafts tree"})
            continue
        contents.append(posixpath.relpath(src.relative_to(root).as_posix(),
                                          posixpath.dirname(page_src) or "."))
        ids.append(nid)
        cats[src.relative_to(root).as_posix()] = categories_of((F.prop(n, "metadata") or {}).get("categories"))
        d = member_updated(n)
        if d is not None:
            dates.append(d)
    return {"contents": contents, "ids": ids, "updated": max(dates).isoformat() if dates else None,
            "cats": cats, "errors": errors}


def _front(
    node: Any,                       # The Series or Lens node
    listing: Dict[str, Any],         # The kind's listing options + this page's contents
    updated: Optional[str],          # The derived date-modified
    categories: Optional[List[str]] = None,
) -> Dict[str, Any]:
    front: Dict[str, Any] = {"title": F.prop(node, "title") or F.prop(node, "key")}
    for key in ("description", "date"):
        if F.prop(node, key):
            front[key] = F.prop(node, key)
    if updated:
        front["date-modified"] = updated
    if categories:
        front["categories"] = categories
    if F.prop(node, "image"):
        front["image"] = F.prop(node, "image")
    front["listing"] = listing
    return front


async def page_plan(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    profile: str,                       # public | staging
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    drafts_dir: Optional[str] = "drafts",  # The drafts tree relative to the root
) -> Dict[str, Any]:  # {pages: [{source, kind, key, subject, members, text}], unpaged, errors}
    """Plan every projected page: a Series or Lens with an active site_path gets one; a broken
    series chain, a truncated Lens selection, or two nodes landing on one file refuse."""
    from .purenotes import note_publish_states, note_types
    root = Path(website_root).resolve()
    drafts = (root / drafts_dir).resolve() if drafts_dir else None
    states = await note_publish_states(gx)
    types = await note_types(gx)
    series = await F.load_label(gx, DevNodeKinds.SERIES)
    lenses = await F.load_label(gx, LENS_LABEL)
    topics = await _tagged_topics(gx, [str(F.nid(s)) for s in series])
    planned: List[Dict[str, Any]] = []
    unpaged: List[str] = []
    from .postpage import load_category_listing
    category = load_category_listing(website_root)   # where every chip links (design a7224060)
    errors: List[Dict[str, Any]] = list(category["errors"])
    matrix_pages: List[Any] = []   # coverage-matrix Lenses, planned after every collection page
    library_pages: List[Any] = []  # the library Lens, planned after them all (its topic line reads them)
    for kind, nodes in ((DevNodeKinds.SERIES, series), (LENS_LABEL, lenses)):
        for node in sorted(nodes, key=lambda n: str(F.prop(n, "key") or "")):
            sid, key = str(F.nid(node)), str(F.prop(node, "key") or "")
            page = pages.get(sid)
            if page is None:
                unpaged.append(f"{kind}:{key}")
                continue
            src = page_source(page["active"])
            if src is None:
                errors.append({"kind": "page-path", "subject": sid, "path": page["active"],
                               "why": "the page's site_path names no page file"})
                continue
            if kind == DevNodeKinds.SERIES:
                order = await series_order(gx, key)
                if order.get("contradictions"):
                    errors.append({"kind": "series-order", "subject": sid, "key": key,
                                   "contradictions": order["contradictions"],
                                   "why": "the series' authored order is broken; the build never guesses one"})
                    continue
                members = list((await F.load_nodes(gx, [m["id"] for m in order["members"]])).values())
                by_id = {str(F.nid(n)): n for n in members}
                members = [by_id[m["id"]] for m in order["members"] if m["id"] in by_id]
                listing, cats, group = dict(SERIES_LISTING), topics.get(sid), None
            else:
                applied = await apply_lens(gx, key)
                if applied.get("error") or applied.get("truncated"):
                    errors.append({"kind": "lens", "subject": sid, "key": key,
                                   "why": applied.get("error") or "the Lens selection was truncated; a page would silently drop members"})
                    continue
                members = [n for n in applied["nodes"] if n.get("label") == DevNodeKinds.NOTE]
                if (applied.get("view") or {}).get("layout") == MATRIX_LAYOUT:
                    # The Tutorials page (design 7f200ecb): its learning paths are read off the
                    # other planned pages, so it is planned after all of them
                    matrix_pages.append((node, members, {"source": src, "href": page["active"]}))
                    continue
                if (applied.get("view") or {}).get("layout") == LIBRARY_LAYOUT:
                    # The Library index (design 638b7b85): its work pages are planned with it
                    library_pages.append((node, {"source": src, "href": page["active"]}))
                    continue
                listing, cats = dict(LENS_LISTING), None
                sort = (applied.get("view") or {}).get("sort")
                if sort:
                    listing = {"sort": list(sort), **listing}
                group = (applied.get("view") or {}).get("group_by")
                if group not in (None, GROUP_SERIES):
                    errors.append({"kind": "lens-group", "subject": sid, "key": key, "group_by": group,
                                   "why": "a site page groups only by series (7657c4a5 (1)); the build never guesses another grouping"})
                    continue
            listed = _listed(members, src, root, profile, states, types, drafts, sid)
            errors += listed["errors"]
            contents = listed["contents"]
            if group == GROUP_SERIES:   # one entry per paged Series (design 7657c4a5 (1))
                grouped = group_through_series(listed["ids"], contents, planned, src, sid)
                errors += grouped["errors"]
                contents = grouped["contents"]
            known = {**listed["cats"], **{p["source"]: p.get("categories") or [] for p in planned}}
            listing = with_category_links({"contents": contents, **listing}, src,
                                          listing_categories(contents, src, known), category["href"])
            planned.append({"source": src, "kind": kind, "key": key, "subject": sid, "categories": cats or [],
                            "members": len(listed["contents"]), "updated": listed["updated"],
                            "listed": listed["ids"], "href": page["active"],
                            "sequence": kind == DevNodeKinds.SERIES,
                            "title": str(F.prop(node, "title") or key),
                            "text": render_page(_front(node, listing, listed["updated"], cats))})
    for node, members, page in matrix_pages:
        got = await plan_matrix_page(gx, node, members, page, root, profile, states, types, drafts,
                                     list(planned), category["href"])
        errors += got.get("errors", [])
        if got.get("page"):
            planned.append(got["page"])
    for node, page in library_pages:
        got = await plan_library_pages(gx, node, page, pages, root, profile, states, types, drafts,
                                       list(planned))
        errors += got.get("errors", [])
        planned += got.get("pages", [])
    seen: Dict[str, str] = {}
    for p in planned:
        if p["source"] in seen:
            errors.append({"kind": "page-collision", "source": p["source"],
                           "subjects": [seen[p["source"]], p["subject"]],
                           "why": "two nodes' site_paths land on one page file"})
        seen[p["source"]] = p["subject"]
    return {"pages": planned, "unpaged": unpaged, "category_listing": category["href"], "errors": errors}


def _generated_files(
    root: Path,  # The site project root (resolved)
) -> List[str]:  # Every marked page in the source tree, relative to the root
    out = []
    for p in root.rglob("*.qmd"):
        rel = p.relative_to(root)
        if any(part in _SKIP_DIRS for part in rel.parts[:-1]):
            continue
        if is_generated(p):
            out.append(rel.as_posix())
    return sorted(out)


async def project_pages(
    gx: GraphHandle,
    website_root: str,                  # The site project root
    profile: str,                       # public | staging
    pages: Dict[str, Dict[str, Any]],   # redirect_plan's {subject: {active, superseded}}
    *,
    drafts_dir: Optional[str] = "drafts",
    write: bool = True,                 # False = plan and check only
) -> Dict[str, Any]:  # {planned, written, unchanged, removed, unpaged, sources, plan, errors}
    """Write the planned pages into the source tree (only those whose text changed), remove
    the marked pages no longer planned, and refuse the whole write when a planned page would
    land on an unmarked file."""
    root = Path(website_root).resolve()
    plan = await page_plan(gx, website_root, profile, pages, drafts_dir)
    errors = list(plan["errors"])
    for p in plan["pages"]:
        dest = root / p["source"]
        if dest.exists() and not is_generated(dest):
            errors.append({"kind": "page-over-source", "source": p["source"], "subject": p["subject"],
                           "why": "a file not generated by the build sits where a projected page lands"})
    rep: Dict[str, Any] = {"planned": len(plan["pages"]), "written": 0, "unchanged": 0, "removed": [],
                           "unpaged": plan["unpaged"], "sources": [p["source"] for p in plan["pages"]],
                           "category_listing": plan.get("category_listing") or "", "plan": plan["pages"]}
    if errors or not write:
        return {**rep, "errors": errors}
    wanted = {p["source"] for p in plan["pages"]}
    for rel in _generated_files(root):
        if rel not in wanted:
            (root / rel).unlink()
            rep["removed"].append(rel)
    tmpl = root / LISTING_TEMPLATE_FILE   # the pages' listing template (design a7224060)
    if not tmpl.exists() or tmpl.read_text(encoding="utf-8") != LISTING_TEMPLATE:
        tmpl.parent.mkdir(parents=True, exist_ok=True)
        tmpl.write_text(LISTING_TEMPLATE, encoding="utf-8")
    for p in plan["pages"]:
        dest = root / p["source"]
        if dest.exists() and dest.read_text(encoding="utf-8") == p["text"]:
            rep["unchanged"] += 1
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(p["text"], encoding="utf-8")
            rep["written"] += 1
        _stamp(dest, p["updated"])
    return {**rep, "errors": errors}


def _stamp(
    dest: Path,              # A projected page file
    updated: Optional[str],  # Its derived date-modified (ISO day), or None
) -> None:
    """Set the page file's mtime to its derived date-modified (midnight UTC). Quarto reads a
    page's file mtime for the sitemap's lastmod and the listings' file-modified key; a generated
    file's mtime would otherwise be whenever a build last wrote it (a profile switch rewrites the
    pages whose draft lists differ), so the derived date is what those fields carry."""
    if not updated:
        return
    ts = datetime.strptime(updated, "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp()
    os.utime(dest, (ts, ts))


def check_page_outputs(
    output_dir: str,     # The profile's output dir
    sources: List[str],  # The projected pages' sources (relative)
) -> List[Dict[str, Any]]:  # Error rows: a projected page the render did not produce
    """Every Series or Lens page the build projected has its rendered page (the guard's check,
    design e240183f (1))."""
    out = Path(output_dir)
    return [{"kind": "page-missing", "source": s, "why": "a projected page did not render"}
            for s in sources if not (out / (s[:-len(".qmd")] + ".html")).exists()]


def categories_of(
    value: Any,  # A front-matter `categories` (a list, one string, or none)
) -> List[str]:  # The categories as Quarto reads them, in order
    if not value:
        return []
    return [str(c) for c in (value if isinstance(value, list) else [value]) if str(c).strip()]


def listing_categories(
    contents: List[str],              # A listing's contents paths, relative to its page
    page_src: str,                    # The page's source, relative to the root
    known: Dict[str, List[str]],      # Source (relative to the root) -> the categories it carries
) -> List[str]:  # Every category the listing's items carry, sorted
    """The categories a listing's chips will show: each listed source's own (a post's front
    matter, a projected page's categories), read through its path relative to the root."""
    out = set()
    for c in contents:
        out.update(known.get(posixpath.normpath(posixpath.join(posixpath.dirname(page_src), c)), []))
    return sorted(out)


def with_category_links(
    listing: Dict[str, Any],  # A projected listing's options (its fields among them)
    page_src: str,            # The page's source, relative to the root
    categories: List[str],    # Every category its items carry (listing_categories)
    listing_href: str,        # The category listing's page path (load_category_listing; "" = none)
) -> Dict[str, Any]:  # The options rendering through the site listing template
    """A projected listing renders through the site listing template (design a7224060): each chip
    links into the category listing filtered to it, every href planned here by the one encoder
    (postpage.category_links). No category listing = no links: the chips are labels."""
    from .postpage import category_links
    params = {"fields": list(listing.get("fields") or []),
              "category-links": {c["name"]: c["href"] for c in category_links(categories, listing_href)}}
    return {**{k: v for k, v in listing.items() if k != "type"},
            "template": posixpath.relpath(LISTING_TEMPLATE_FILE, posixpath.dirname(page_src) or "."),
            "template-params": params}


def check_listing_chips(
    output_dir: str,     # The profile's output dir
    sources: List[str],  # The projected pages' sources (relative)
) -> List[Dict[str, Any]]:  # Error rows: a chip the build planned no link for
    """After the render, with a category listing named: every chip on a projected page is a link
    (the template renders a category with no planned href as a label div) -- fails closed."""
    out = Path(output_dir)
    errors = []
    for s in sources:
        page = out / (s[:-len(".qmd")] + ".html")
        n = page.read_text(encoding="utf-8").count('<div class="listing-category">') if page.exists() else 0
        if n:
            errors.append({"kind": "chip-unlinked", "source": s, "chips": n,
                           "why": "a listing chip the build planned no category link for"})
    return errors


def group_through_series(
    ids: List[str],                     # The Lens page's listed members, in listing order
    contents: List[str],                # Their contents paths (relative to the page), same order
    planned: List[Dict[str, Any]],      # The pages planned so far (every Series page among them)
    page_src: str,                      # The Lens page's source, relative to the root
    subject: str,                       # The Lens node's id (error rows name it)
) -> Dict[str, Any]:  # {contents, errors}
    """A Lens with view.group_by "series" lists a member THROUGH its Series page (design 7657c4a5
    (1)): one entry per paged Series, in the place of its first member, a member in no paged Series
    as itself. A member two paged Series list refuses -- the build never picks one."""
    pages: Dict[str, List[str]] = {}
    for p in planned:
        if p.get("sequence") and p.get("kind") == DevNodeKinds.SERIES:
            for m in p["listed"]:
                pages.setdefault(m, []).append(p["source"])
    out: List[str] = []
    errors: List[Dict[str, Any]] = []
    for nid, path in zip(ids, contents):
        srcs = pages.get(nid) or []
        if len(srcs) > 1:
            errors.append({"kind": "lens-group", "subject": subject, "member": nid, "series_pages": srcs,
                           "why": "a member two paged Series list; the build never picks one to group it under"})
            continue
        entry = posixpath.relpath(srcs[0], posixpath.dirname(page_src) or ".") if srcs else path
        if entry not in out:
            out.append(entry)
    return {"contents": out, "errors": errors}
